repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: examples
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
        exclude: examples
      - id: end-of-file-fixer
        exclude: examples
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: examples
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=88]
        exclude: examples
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --line-length=88]
        exclude: examples
